name: .NET Core Desktop

on: workflow_dispatch

jobs:

  build:
    permissions: write-all


    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
    - name: pack
      run: dotnet pack
      working-directory: PowerCollections
    - name: push
      run: dotnet nuget push "*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/VSynV/index.json --skip-duplicate
      working-directory: PowerCollections/PowerCollections/bin/Debug
    - name: Get XML Info
  # You may pin to the exact commit or the version.
  # uses: mavrosxristoforos/get-xml-info@749cc7ecda18372226181a390717a4cab5439eb5
      uses: mavrosxristoforos/get-xml-info@1.1.1
      with:
    # The xml file from which to retrieve information.
          xml-file: PowerCollections/PowerCollections/PowerCollections.csproj
    # The XPath of a node, to fetch its contents as output.
          xpath: //Version      
    - name: Create Release 
      uses: ncipollo/release-action@v1.12.0
      with: 
        artifacts: 'PowerCollections\PowerCollections\bin\Debug\*${{ steps.getxml.outputs.info }}.nupkg'
        tag: 'v ${{ steps.getxml.outputs.info }}'
