name: .NET Core Desktop

on:
  push:
    branches: [ "Task03" ]

jobs:

  build:

    runs-on: windows-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: execute build
      run: dotnet build
      working-directory: PowerCollections

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test
      working-directory: PowerCollections
      
